/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CostomForm: typeof import('./components/Form/CostomForm/index.vue')['default']
    Dialog: typeof import('./components/dialog/Dialog.vue')['default']
    Echarts: typeof import('./components/echarts/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconEpExpand: typeof import('~icons/ep/expand')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    LoadMore: typeof import('./components/LoadMore/index.vue')['default']
    Menus: typeof import('./components/Menus/index.vue')['default']
    RightMenus: typeof import('./components/RightMenus/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svgIcon/index.vue')['default']
    Tab: typeof import('./components/Tab/index.vue')['default']
    Tabs: typeof import('./components/Tab/Tabs.vue')['default']
    TimeLine: typeof import('./components/TimeLine/index.vue')['default']
  }
}
